### ISSUE TITLE
Makefile not working on GitHub build extension action

### ISSUE THREAD

**Issue by erikng** [macadmins/osquery-extension#40]
I merged a PR to make a new release, but it's failing when running the "clean" portion of the makefile. I'm not sure why "rm -rf" cares that the folder doesn't exist and exits 2, but it triggers the job to fail.

**Comment by erikng** [comment]
I'll try and work on it tomorrow if no one has any ideas.

**Comment by roperzh** [comment]
the root cause seems to be the [BUILD](https://github.com/macadmins/osquery-extension/blob/main/BUILD) file at the root of the repo, and the fact that the worker is probably running in a file system that's case insensitive.

I'm able to repro locally on my macOS machine, I get the same error even trying to create a directory with the name `build`:

```
$ mkdir -p build/linux
mkdir: build: Not a directory

~/vendor/osquery-extension $ rm -rf BUILD

~/vendor/osquery-extension $ mkdir -p build/linux
```

I'm not familiar with Bazel at all, but form [the docs](https://bazel.build/concepts/build-files):

> Note: The BUILD file can be named either BUILD or BUILD.bazel. If both files exist, BUILD.bazel takes precedence over BUILD. For simplicity's sake, the documentation refers to these files simply as BUILD files.

I can submit a PR giving that a try

**Comment by roperzh** [comment]
I'm not 100% sure that will work, but in the meantime I submitted a PR with the rename: https://github.com/macadmins/osquery-extension/pull/41

**Comment by roperzh** [comment]
After installing Bazel, I can confirm that I was able to run `make build` successfully with the changes in the PR. I will note this in the PR as well

**Comment by erikng** [comment]
It worked. New release is out.

**Comment by roperzh** [comment]
thank you!
